name: action test
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install:
    name: action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mashiike/clipsight@main
        with:
          version: v0.2.0
      - run: |
          clipsight version 2>&1 | fgrep v0.2.0
      - uses: mashiike/clipsight@main
        with:
          version: latest
      - run: |
          clipsight version 2>&1 | fgrep v0
