name: action test
on:
  push:
    branches:
      - v0
  workflow_dispatch:

jobs:
  install:
    name: action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mashiike/clipsight@v0
        with:
          version: v0.2.0
      - run: |
          clipsight version 2>&1 | fgrep v0.2.0
      - uses: mashiike/clipsight@v0
        with:
          version: latest
      - run: |
          clipsight version 2>&1 | fgrep v0
